### ISSUE TITLE
Using a question mark (?) before content type is a PHP 7.1 feature

### ISSUE THREAD

**Issue by reazuliqbal** [edsonmedina/bittrex#7]
> Type declarations for parameters and return values can now be marked as nullable by prefixing the type name with a question mark. This signifies that as well as the specified type, NULL can be passed as an argument, or returned as a value, respectively.

Source: [http://php.net/manual/en/migration71.new-features.php](http://php.net/manual/en/migration71.new-features.php)

In the composer.json of this project, this project requires PHP 7.0 or higher. Adding a question mark is supported on PHP 7.1 but not on PHP 7.0. I tested on my machine which runs _PHP 7.0.22-0ubuntu0.16.04.1_ . I don't know if everybody running PHP 7.0 is facing the same issue.

If everybody does then we should change the composer or make the project PHP 7.0 compatible by removing those question marks.

**Comment by edsonmedina** [comment]
There's no composer package for this class, so I don't know what you're referring to.

**Comment by reazuliqbal** [comment]
I am very sorry for my very vague message. I was talking about the redesign Branch. I am adding an example code (Line 142-159) form the file [redesign/src/Account.php](https://github.com/edsonmedina/bittrex/blob/redesign/src/Account.php#L142)

```php
    public function withdraw(Money $amount, Address $address, ?string $paymentId = null): string
    {
        if ($amount->getCurrency() !== $address->getCurrency()) {
            throw new \InvalidArgumentException('Address currency doesn\'t match the transaction currency');
        }
        $extraParams = [
            'currency' => $amount->getCurrency(),
            'quantity' => sprintf('%0.8f', $amount->getValue()),
            'address'  => $address,
        ];
        if ($paymentId !== null) {
            $extraParams['paymentid'] = $paymentId;
        }
        return $this->call('account/withdraw', $extraParams)->uuid;
    }
```
In the `withdraw()` function for the property type of `$paymentId`, you wrote a `?` before the type `string` to represent it can be a `NULL` value. This is supported in `PHP 7.1` but not on `PHP 7.0`.

In the `composer.json` file you mentioned this project require `"php": ">=7.0"`. So think we should change it to `"php": ">=7.1",`.

Once again I am very sorry for my vague response and I am also not a PHP programmer, I just understand it a little. So, ignore it, if I am wrong.

**Comment by edsonmedina** [comment]
Ah! Good point.

I've changed it. Thanks.
