### ISSUE TITLE
There's No autoload.php

### ISSUE THREAD

**Issue by dci39384** [edsonmedina/bittrex#8]
Hey, I just tried the script, the '/vendor/autoload.php is missing, any suggestions?

Thanks!

**Comment by edsonmedina** [comment]
Run `composer install` first

**Comment by dci39384** [comment]
Thanks, it got resolved, i'm trying to get balance, etc.. it shows up an error saying: PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE)
in /var/www/html/2/src/Account.php on line 142

**Comment by edsonmedina** [comment]
You need php 7.1

**Comment by dci39384** [comment]
Strange, i'm already running v 7.1
PHP 7.1.13-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Jan  5 2018 13:26:45) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.13-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies

**Comment by dci39384** [comment]
Got it resolved. Just please provide me with a sample on how to order a coin.

Thanks in advance :)

**Comment by dci39384** [comment]
BTW, i'm using the re-design one
